#pragma once
/* Auto-generated by tools/gen_version.py - do not edit. */

#define WKAL_BASE_VERSION "0.4.0"
#define WKAL_BUILD_TYPE "dev"
#define WKAL_BUILD_SUFFIX "20260929092605"
#define WKAL_FULL_VERSION "0.4.0-relapse-13x"
#define WKAL_BUILD_TIME "2026-09-29 09:26:05 UTC"
